### ISSUE TITLE
ProtocolHack Error

### ISSUE THREAD

**Issue by Kurimatzu** [InventivetalentDev/NickNamer#10]
`[11:39:27 ERROR]: [NickNamer] Failed to disguise profile
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
        at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:136) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfile(SkinLoader.java:106) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.PacketListener.disguiseProfile(PacketListener.java:284) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.PacketListener.onSend(PacketListener.java:101) [NickNamer.jar:?]
        at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:109) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:146) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:111) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.channel.NMUChannel$ChannelHandler.write(NMUChannel.java:168) [PacketListenerAPI.jar:?]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) [spigot.jar:git-DreamSpigotPlus-549b970]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:310) [ProtocolLib.jar:?]
        at net.minecraft.server.v1_7_R4.QueuedProtocolSwitch.run(SourceFile:143) [spigot.jar:git-DreamSpigotPlus-549b970]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:327) [ProtocolLib.jar:?]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [spigot.jar:git-DreamSpigotPlus-549b970]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
[11:39:27 ERROR]: [NickNamer] Failed to disguise profile
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
        at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:136) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfile(SkinLoader.java:106) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.PacketListener.disguiseProfile(PacketListener.java:284) ~[NickNamer.jar:?]
        at org.inventivetalent.nicknamer.api.PacketListener.onSend(PacketListener.java:101) [NickNamer.jar:?]
        at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:109) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:146) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:111) [PacketListenerAPI.jar:?]
        at org.inventivetalent.packetlistener.channel.NMUChannel$ChannelHandler.write(NMUChannel.java:168) [PacketListenerAPI.jar:?]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) [spigot.jar:git-DreamSpigotPlus-549b970]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:310) [ProtocolLib.jar:?]
        at net.minecraft.server.v1_7_R4.QueuedProtocolSwitch.run(SourceFile:143) [spigot.jar:git-DreamSpigotPlus-549b970]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:327) [ProtocolLib.jar:?]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [spigot.jar:git-DreamSpigotPlus-549b970]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [spigot.jar:git-DreamSpigotPlus-549b970]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
>`

This error occurred when entering /nick using protocol hack in a client 1.8.

**Comment by InventivetalentDev** [comment]
Please use the provided issue template and fill in all the details asked for. Also use pastebin or hastebin to upload the error.
