### ISSUE TITLE
will not generate a file for the config and stuff

### ISSUE THREAD

**Issue by CookieManPlayz** [InventivetalentDev/NickNamer#110]
## What steps will reproduce the problem?  
1. 
2. 
3.

**Comment by Th3Shadowbroker** [comment]
Hi @cookieman27, 
please provide a server-log file via [pastebin](https://pastebin.com/)

**Comment by cookieman27** [comment]
my log is to big it says I have reached maximum word limit

**Comment by Th3Shadowbroker** [comment]
Please create a new log then or upload your logfile here on github.

**Comment by cookieman27** [comment]
[latest.log](https://github.com/InventivetalentDev/NickNamer/files/4428220/latest.log)
ok there
i serched for nickname/nick and nothing came up in the document so idk

**Comment by Th3Shadowbroker** [comment]
Alright. I need a fresh and clean log-file here. I'm not surprised your log-file is so big. A plugin called EntityTrackerFixer is permanently causing exceptions. Please remove this plugin and delete/rename the latest.log file before restarting your server to generate a new and fresh log-file.

```
[00:00:47] [Server thread/WARN]: [EntityTrackerFixer] Task #9 for EntityTrackerFixer v1.2.2 generated an exception
java.lang.NoSuchFieldError: recentTps
	at net.minemora.entitytrackerfixer.v1_15_R1.tasks.UntrackerTask.run(UntrackerTask.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:393) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:985) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:940) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:789) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
```

**Comment by cookieman27** [comment]
i need the entitytrackerfix or my server will crash because of lag so I just made a new of file restarted the server and got a fresh file with only 2 errors form the plugin
[latest (1).log](https://github.com/InventivetalentDev/NickNamer/files/4428452/latest.1.log)

**Comment by Th3Shadowbroker** [comment]
Alright, thanks for the log. It seems you haven't installed [PacketListenerAPI](https://www.spigotmc.org/resources/api-packetlistenerapi.2930) which is required to run NickNamer.

```
[11:56:00] [Server thread/ERROR]: Could not load 'plugins/NickNamer_v3.18.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PacketListenerApi
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:351) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:204) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [craftbukkit_1.15.2.jar:git-Bukkit-4d975ac]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by cookieman27** [comment]
thanks it worked! it displays in tab but not in chat, is there a option that fixes that in the config

**Comment by Th3Shadowbroker** [comment]
If `replace > chat > player` is already true, try setting `replace > chat > out` to true

```yaml
replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: false
    in:
      # Replace real names in incoming commands with the player's nickname
      command: false
      # Replace incoming command nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      commandReverse: false

      # Replace real names in general (non-command) incoming messages with the player's nickname
      general: false
      # Replace incoming nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      generalReverse: false
  scoreboard: false
  scoreboardScore: false
  scoreboardTeam: false
  tabComplete:
    chat: false
```
