### ISSUE TITLE
Error occurred while enabling NickNamer

### ISSUE THREAD

**Issue by guerrilha77** [InventivetalentDev/NickNamer#122]
## What were you expecting to happen? What happened instead?  
I´m installed the plugin and api, but the server could not enable it. I tried many versions of the plugin.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
I tried many versions 

## What Spigot version are you using? *Type /version*  
spigot version v1_12_R1

https://hatebin.com/erwssicsds

**Comment by guerrilha77** [comment]
[22:16:18] [Server thread/INFO]: [PacketListenerApi] Enabling PacketListenerApi v3.7.6-SNAPSHOT
[22:16:18] [Server thread/INFO]: Adding channels for online players...
[22:16:18] [Server thread/INFO]: [NickNamer] Enabling NickNamer v3.18.2-SNAPSHOT
[22:16:18] [Server thread/INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.nicknamer.reflection.minecraft
[22:16:18] [Server thread/INFO]: [ReflectionHelper] Version is v1_12_R1 (11201)
[22:16:18] [Server thread/ERROR]: Error occurred while enabling NickNamer v3.18.2-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.inventivetalent.nicknamer.api.NickNamerAPI.init(NickNamerAPI.java:140) ~[?:?]
        at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:55) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:96) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:127) ~[?:?]
        at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-fa590fd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-fa590fd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-CatServer-1.12.2-fa590fd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433) [CraftServer.class:git-CatServer-1.12.2-fa590fd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382) [CraftServer.class:git-CatServer-1.12.2-fa590fd]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: class cannot be null
        at org.inventivetalent.nicknamer.reflection.resolver.MemberResolver.<init>(MemberResolver.java:20) ~[?:?]
        at org.inventivetalent.nicknamer.reflection.resolver.MethodResolver.<init>(MethodResolver.java:14) ~[?:?]
        at org.inventivetalent.nicknamer.api.PacketListener.<clinit>(PacketListener.java:68) ~[?:?]
        ... 14 more

**Comment by InventivetalentDev** [comment]
What Java version are you using?
