### ISSUE TITLE
1.12.2 server PacketListener spamming console anytime someone's online

### ISSUE THREAD

**Issue by Ace-Monkey-Ilium** [InventivetalentDev/NickNamer#137]
## What steps will reproduce the problem?  
1. PlacketListner spams
2. 
3. 

## What were you expecting to happen? What happened instead?  

I was expecting it to work properly

## What Spigot version are you using? *Type /version*  

[https://cdn.discordapp.com/attachments/432005289626173450/754519036800401428/Screen_Shot_2020-09-13_at_10.48.51_AM.jpg](https://cdn.discordapp.com/attachments/432005289626173450/754519036800401428/Screen_Shot_2020-09-13_at_10.48.51_AM.jpg)

## What plugins are you using? *Type /plugins*  

47 different plugins. 

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

[01:45:46 WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin NickNamer: java.util.HashSet cannot be cast to java.util.List
[01:45:46 WARN]: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
[01:45:46 WARN]:        at org.inventivetalent.nicknamer.api.PacketListener.onSend(PacketListener.java:215)
[01:45:46 WARN]:        at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:81)
[01:45:46 WARN]:        at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:118)
[01:45:46 WARN]:        at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:85)
[01:45:46 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:140)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[01:45:46 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[01:45:46 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener$1.write(PacketListener.java:64)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[01:45:46 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[01:45:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[01:45:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[01:45:46 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[01:45:46 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[01:45:46 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[01:45:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[01:45:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[01:45:46 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[01:45:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[01:45:46 WARN]:        at java.lang.Thread.run(Thread.java:748)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

It didn't crash, the server just spammed console

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

I'm not using bungee cord and it worked on my dev server.

**Comment by Ace-Monkey-Ilium** [comment]
It seems to have problems with pretty much any scoreboard plugins out there.
