### ISSUE TITLE
Could not load 'plugins\NickNamer_v3.21.0-SNAPSHOT.jar' in folder plugins

### ISSUE THREAD

**Issue by AhmadNF0** [InventivetalentDev/NickNamer#161]
help

org.bukkit.plugin.UnknownDependencyException: Unknown dependency PacketListenerApi. Please download and install PacketListenerApi to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by Th3Shadowbroker** [comment]
Hi @AhmadNF0,
the solution for your problem is literally written there in line 1 🧐 

>**Unknown dependency PacketListenerApi. Please download and install PacketListenerApi to run this plugin.**

**Comment by AhmadNF0** [comment]
PacketListenerApi it gives me the same error

**Comment by AhmadNF0** [comment]
Could not load 'plugins\NickNamer_v3.21.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency PacketListenerApi. Please download and install PacketListenerApi to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:183) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by AhmadNF0** [comment]
> 
> 
> Hi @AhmadNF0,
> the solution for your problem is literally written there in line 1 🧐
> 
> > **Unknown dependency PacketListenerApi. Please download and install PacketListenerApi to run this plugin.**

help

 Could not load 'plugins\PacketListenerAPI_v3.9.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/inventivetalent/packetlistener/PacketListenerPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:183) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.UnsupportedClassVersionError: org/inventivetalent/packetlistener/PacketListenerPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_291]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_291]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 7 more

**Comment by Th3Shadowbroker** [comment]
That definitely isn't the same error as the one from NickNamer, but I've seen that before in #157 👀 
Have a look at [this](https://github.com/InventivetalentDev/NickNamer/issues/157#issuecomment-840453841) comment.
