### ISSUE TITLE
Error loading plugin NickNamer

### ISSUE THREAD

**Issue by RiseCraft-ViorisE** [InventivetalentDev/NickNamer#163]
## What steps will reproduce the problem?  
1. Installing the plugin
2. Plugin folder
3. Restart Bungee

## What were you expecting to happen? What happened instead?  
The plugin should've started normally.

This happend
Error loading plugin NickNamer
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.21.1

## What Spigot version are you using? *Type /version*  
1.8.8

## What plugins are you using? *Type /plugins*  
AdvancedBan, AdvancedNMotd, ajQueue, BReport, bStats, BungeeGuard, BungeeTabListPlus, CraftingStore, gChat, Lobbysystem, LuckPerms, ViaVersion

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes I'm using bungeecord, I used it on a spigot server (so not on a bungee), and it worked correctly.
I also use the latest version of PacketListener Api.

**Comment by Th3Shadowbroker** [comment]
Hey @RiseCraft-ViorisE,

>Yes I'm using bungeecord, I used it on a spigot server (so not on a bungee), and it worked correctly.
I also use the latest version of PacketListener Api.

did I understand that correctly? You originally used it on Spigot (where it worked) and now you're running it on a Bungeecord server right? NickNamer itself requires Spigot or Paper (and Java 11 or above). You can then install the [Bungee Synchronizer](https://www.spigotmc.org/resources/nicknamer-bungee-synchronizer.8964/) on your Bungee, to Synch nicknames across servers.

**Comment by RiseCraft-ViorisE** [comment]
Ohhh okay.

I probably miss-understood the documentation. Now I get it.
Thanks for your help, I was really confused by the error.

**Comment by Th3Shadowbroker** [comment]
No problem 🙂
Always happy to help 👍🏻
