### ISSUE TITLE
NICKNAMER ERROR

### ISSUE THREAD

**Issue by HiperBulu** [InventivetalentDev/NickNamer#2]
What steps will reproduce the problem?

When a player die
When a player disguise
What version of the plugin are you using? Type /version <Plugin Name>

[15:08:35 INFO]: NickNamer version 3.8.1
[15:08:35 INFO]: Author: inventivetalent

What Spigot version are you using? Type /version

[15:06:16 INFO]: This server is running CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[15:06:17 INFO]: You are 75 version(s) behind

What plugins ae you using? Type /plugins

[15:06:51 INFO]: Plugins (18): ResourcePackApi, WorldEdit, Skript, Essentials, EssentialsChat, BossBarAPI, PacketListenerApi, PermissionsEx, ItemBuilder, ParticleLIB, EssentialsSpawn, PlayerVersion, TitleAPI, NickNamer, MenuBuilder, EntityAnimationAPI, NPCLib, Murder

Do you have an error log? Use pastebin.com. If you're not sure, upload your whole server lo

http://pastebin.com/stmRrDMK

Did your client crash? Upload errors in .minecraft/logs/latest.log as well

No

Additional information? (Are you using Bungeecord? Did it work in previous versions? etc.)

Don't work with any version

ERROR:
[15:02:41] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0"
[15:02:41] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin NickNamer v3.8.1 generated an exception while executing task 91
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.inventivetalent.nicknamer.NickNamerPlugin$6.run(NickNamerPlugin.java:360)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by HiperBulu** [comment]
Resolved
