### ISSUE TITLE
NickNamer is Broken on 1.12 Spigot

### ISSUE THREAD

**Issue by tommylee464** [InventivetalentDev/NickNamer#57]
## What steps will reproduce the problem?  
1. install the plugin
2. install the dependency
3. start your server
4 error while enabling NickNamer...

## What were you expecting to happen? What happened instead?  
in 1.11 work good in 1.12 d'ont work
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
i have uploaded the latest plugin of NickNamer
## What Spigot version are you using? *Type /version*  
Spigot 1.12
## What plugins are you using? *Type /plugins*  
WorldEdit, LoginSecurity, PacketListenerApi, Multiverse-Core, WorldGuard, Multiverse-Inventories, ViaVersion, mcMMO, Vault, ViaBackwards, MassiveCore, NickNamer, Essentials, CustomSkins, Jobs, PerWorldInventory, CreativeGates, ProtocolLib, NoCheatPlus, EssentialsXMPP, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, Orebfuscator4, Factions

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/uB5Ph9nC

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
no

**Comment by scarabcoder** [comment]
The "local" storage option is no longer supported. Bukkit dropped support for EBean servers as part of the JavaPlugin class.

Pull request created, fixed these errors @InventivetalentDev .

**Comment by benni-germany** [comment]
Please fix it
(-: 
@InventivetalentDev

**Comment by Doc94** [comment]
Still broken

**Comment by scarabcoder** [comment]
Compile from here, I updated it: https://github.com/InventivetalentDev/NickNamer/pull/58

InventivTalent doesn't update her plugins anymore (except a few of the largest).

**Comment by Doc94** [comment]
@scarabcoder well i try build this but i have error from pom :/
Any build generate in this fork?

**Comment by benni-germany** [comment]
It doesnt work. 
It does not generate a config file/Folder, and the Command Output is only Empty.
Am I using it wrong or is this an error?
Screenshot: http://prntscr.com/g5k40j

**Comment by scarabcoder** [comment]
@benni-germany Try switching the file storage type to MySQL or something else other than the default.

**Comment by benni-germany** [comment]
But there is no Config file, where i could change it?

**Comment by scarabcoder** [comment]
@benni-germany Check the server logs.

**Comment by benni-germany** [comment]
>[2K
[21:09:09 INFO]: [NickNamer] Enabling NickNamer v3.13.2-SNAPSHOT
>[2K
[21:09:09 ERROR]: Error occurred while enabling NickNamer v3.13.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/inventivetalent/packetlistener/PacketListenerAPI
        at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:749) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-7228328-e03b1a5]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by scarabcoder** [comment]
@benni-germany You need to also have PacketListenerAPI as a plugin loaded on the server.

**Comment by benni-germany** [comment]
Thak you so much!!
But why did you not add the Commands into plugin.yml?

**Comment by scarabcoder** [comment]
@benni-germany Because they were already there?

**Comment by sergisala** [comment]
@scarabcoder Excuse me. I am having a problem.

I am getting these two errors: 

-one that appears and logs when a player logs on the server -and the PlayerJoinEvent cannot be passed-) 
-Another one that appears when I attempt to execute the /createcustomskin command of the "CustomSkins" Spigot Plugin.

Check my pastebin, please: https://pastebin.com/1p0zXZCy

Thank you,
Sergi

**Comment by scarabcoder** [comment]
@sergisala What data storage method are you using? The default no longer works.
The only change from the previous version was removing all references to the EBean server API in JavaPlugin.

**Comment by sergisala** [comment]
Oh fuck. I was using temporary storage. Let me try with the local one haha @scarabcoder

Thanks for answering me :)

**Comment by sergisala** [comment]
@scarabcoder I've used sql and local and they don't work anyways... :'(

https://pastebin.com/
