### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by DDuart** [InventivetalentDev/NickNamer#76]
## What steps will reproduce the problem?  
Just enable mysql in config

## What were you expecting to happen? What happened instead?  
the table has not been created.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.15.0

## What Spigot version are you using? *Type /version*  
1.12.2

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/raw/mpVkYVyP

**Comment by Th3Shadowbroker** [comment]
Hi @DDuart,
I've tried to reproduce the reported issue without success. I used the following configuration:
```
storage:
  # Storage type
  # - temporary
  #     saves all data in memory until the server is stopped
  # - local (recommended)
  #     creates a local database
  # - sql
  #     uses an SQL server
  # - redis
  #     uses a Redis server
  type: "sql"
  sql:
    address: "jdbc:mysql://localhost:3306/nicknamerdb"
    user: "nicknamer"
    pass: "somepassword"
  redis:
    host: "localhost"
    port: 6379
    pass: ""
    max-connections: 4
```
are there any other suspicous messages in the log?

**Comment by DDuart** [comment]
@Th3Shadowbroker 

```
[09:20:55] [pool-24-thread-14/WARN]: Exception in thread "pool-24-thread-14" java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nicknamerdb.nicknamer_data_nick' doesn't exist
[09:20:55] [pool-24-thread-14/WARN]: 	at org.inventivetalent.data.sql.SQLDataProvider.lambda$get$5(SQLDataProvider.java:156)
[09:20:55] [pool-24-thread-14/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:20:55] [pool-24-thread-14/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:20:55] [pool-24-thread-14/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:20:55] [pool-24-thread-14/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nicknamerdb.nicknamer_data_nick' doesn't exist
[09:20:55] [pool-24-thread-14/WARN]: 	at sun.reflect.GeneratedConstructorAccessor240.newInstance(Unknown Source)
[09:20:55] [pool-24-thread-14/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:20:55] [pool-24-thread-14/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[09:20:55] [pool-24-thread-14/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
[09:20:55] [pool-24-thread-14/WARN]: 	at org.inventivetalent.data.sql.SQLDataProvider.lambda$get$5(SQLDataProvider.java:151)
[09:20:55] [pool-24-thread-14/WARN]: 	... 3 more
```

config:
```
  type: "sql"
  sql:
    address: "jdbc:mysql://s1.domain.com:3306/nicknamerdb"
    user: "nicknamerdb"
    pass: "pass"
```
