### ISSUE TITLE
NickNamer doesn't work on 1.14

### ISSUE THREAD

**Issue by Pixelcraftian** [InventivetalentDev/NickNamer#93]
## What steps will reproduce the problem?  
1. Run a server on 1.14 Paper
2. 
3. thats it

## What were you expecting to happen? What happened instead?  
Was expecting it to work normally like every plugin, but turns out an internal error happened.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
v3.16.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
It's not Spigot but it can run Spigot plugins. Says it's version git-Paper-209 (MC:1.14.4)

## What plugins are you using? *Type /plugins*  
Citizens, CitizensCMD, CleanroomGenerator, CommandSpy, CoreProtect, CustomCrafting, CustomEnderChest, dtlTraders, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastASyncWorldEdit, HeadDataBase, Holograms, LuckPerms, Multiverse (all types), OldCombatMechanics, OpenInv, PerWorldInventory, PlotSquared, PlugMan, Sentinel, Shopkeepers, SimpleSit, SuperVanish, Vault, WolfyUtilites, WorldEdit, WorldGuard

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log* 
no.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Not using BungeeCord, haven't used it before.

**Comment by InventivetalentDev** [comment]
> turns out an internal error happened

Well, please post that then.

**Comment by Pixelcraftian** [comment]
> > turns out an internal error happened
> 
> Well, please post that then.

![Screenshot_182](https://user-images.githubusercontent.com/17987696/69092054-7f1e4c00-0a43-11ea-97e6-fa363411852b.png)

**Comment by Th3Shadowbroker** [comment]
Is there any other error message before this one? Something like:
```
[21:43:13 ERROR]: [NickNamer] Please use Java 8 or higher (is 0)
[21:43:13 ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] NickNamer requires Java 8+ initializing NickNamer v3.16.0-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: NickNamer requires Java 8+
        at org.inventivetalent.nicknamer.NickNamerPlugin.onLoad(NickNamerPlugin.java:160) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-226]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Just asking, because I'm currently investigating the recent post on #83. Both problems might be related to each other.

**Comment by Pixelcraftian** [comment]
> Is there any other error message before this one? Something like:
> 
> ```
> [21:43:13 ERROR]: [NickNamer] Please use Java 8 or higher (is 0)
> [21:43:13 ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] NickNamer requires Java 8+ initializing NickNamer v3.16.0-SNAPSHOT (Is it up to date?)
> java.lang.RuntimeException: NickNamer requires Java 8+
>         at org.inventivetalent.nicknamer.NickNamerPlugin.onLoad(NickNamerPlugin.java:160) ~[?:?]
>         at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-226]
>         at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-226]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-226]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> ```
> 
> Just asking, because I'm currently investigating the recent post on #83. Both problems might be related to each other.

Not that I know of.

**Comment by Th3Shadowbroker** [comment]
Could you please provide the full server-log via pastebin? 
Also please ensure, that you're using the [latest release](https://github.com/InventivetalentDev/NickNamer/releases) of NickNamer. #95 Introduced some changes that might solve your problem. Please try that and report back if the problem still persists 🙂

**Comment by Pixelcraftian** [comment]
> Could you please provide the full server-log via pastebin?
> Also please ensure, that you're using the [latest release](https://github.com/InventivetalentDev/NickNamer/releases) of NickNamer. #95 Introduced some changes that might solve your problem. Please try that and report back if the problem still persists 🙂

**```
[Pterodactyl Daemon] Server marked as ON
[14:43:17 INFO]: Timings Reset
[14:43:18 INFO]: [Citizens] Loaded 3 NPCs.
[14:43:18 INFO]: [Holograms] Loaded hologram with "spawntext" with 1 lines
[14:43:19 INFO]: [HeadDatabase] Succesfully loaded 26609 heads!
[14:43:19 INFO]: [HeadDatabase] Succesfully loaded 18 featured tags!
[14:43:26 INFO]: UUID of player Redorka is 4230147e-727e-47e8-8e00-56f20316e1a5
[14:43:26 INFO]: Redorka[/2.93.31.81:50059] logged in with entity id 327 at ([world]-248.30000001192093, 18.0, -96.03535978838245)
[14:52:31 INFO]: UUID of player Pixelcraftian is 1805e857-329e-463e-8ca8-122fcc686996
[14:52:31 INFO]: Pixelcraftian[/81.158.126.218:52375] logged in with entity id 908 at ([world]-246.1201107182984, 17.0, -99.9760406435624)
[14:52:33 INFO]: Pixelcraftian issued server command: /gmc
[14:52:37 INFO]: Pixelcraftian issued server command: /nicknamer
[14:52:37 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'nicknamer' in plugin NickNamer v3.16.1-SNAPSHOT - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```**

Also, I checked and the line of code you sent isn't on my logs.

**Comment by InventivetalentDev** [comment]
That's literally the same thing you posted already. Please look for any errors in the server's startup and post those. The plugin wasn't enabled properly so there is certainly a error from NickNamer somewhere before that.

**Comment by Pixelcraftian** [comment]
> That's literally the same thing you posted already. Please look for any errors in the server's startup and post those. The plugin wasn't enabled properly so there is certainly a error from NickNamer somewhere before that.

Will do next time I reload the server.

**Comment by Pixelcraftian** [comment]
> > That's literally the same thing you posted already. Please look for any errors in the server's startup and post those. The plugin wasn't enabled properly so there is certainly a error from NickNamer somewhere before that.
> 
> Will do next time I reload the server.

```
[13:41:34 INFO]: [NickNamer] Loading NickNamer v3.16.1-SNAPSHOT
[13:41:34 INFO]: [NickNamer] Java Version: 1.8.0_212
[13:41:34 ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] org/inventivetalent/packetlistener/PacketListenerAPI initializing NickNamer v3.16.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/inventivetalent/packetlistener/PacketListenerAPI
at org.inventivetalent.nicknamer.NickNamerPlugin.onLoad(NickNamerPlugin.java:168) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.inventivetalent.packetlistener.PacketListenerAPI
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
```

Found this part of stuff.

**Comment by Th3Shadowbroker** [comment]
Looks like [PacketListener](https://download.inventivetalent.org/gh/PacketListenerAPI/3.7.5-SNAPSHOT) isn't installed 🤔

**Comment by Pixelcraftian** [comment]
> Looks like [PacketListener](https://www.spigotmc.org/resources/api-packetlistenerapi.2930/) isn't installed/loaded to runtime 🤔

So do I downlaod that?

**Comment by Th3Shadowbroker** [comment]
Yep, please install that plugin and report back if the problem still persists after installing PacketListenerAPI or if it solved the problem 🙂

**Comment by Pixelcraftian** [comment]
> Yep, please install that plugin and report back if the problem still persists after installing PacketListenerAPI or if it solved the problem 🙂

Tried changing the skins of another player to "Steve" but it doesn't autofill, and when I do the command it sometimes doesn't work. It's weird but I'll get used to the sometimes don't work, but please make sure it can autofill in future :)

**Comment by Pixelcraftian** [comment]
Also, I hope it can do @a
